### ISSUE TITLE
How you recommend organize model folder with multi-level STI?

### ISSUE THREAD

**Issue by sovetnik** [ClosureTree/closure_tree#107]
At first, thanks for gem.

I work on structure with multi level STI, where type (class) of node - his parent name,  for example: cent has a path Primitive/Mean/Numerically/Currency/Euro/Cent,
where Mean.class - Primitive,
Numerically.class - Mean,
Currency.class - Numerically, 
Euro & Cent class - Currency.

How i can organize app/models to achieve structure like this?
models/primitive.rb
models/primitives/mean.rb
models/primitives/means/numerically/currency.rb

**Comment by simo163** [comment]
@mceachen very close to this issue, how can I generate hierarchies of a namespaced model? I tried this but did not work:

```
rails g closure_tree:migration Spree::Taxon
```

**Comment by mceachen** [comment]
Sorry but I don't have time to give free support to commercial
applications. Good luck.
