### ISSUE TITLE
Postpone configuration (database introspection)

### ISSUE THREAD

**Issue by Envek** [ClosureTree/closure_tree#264]
Please consider to do database introspection not when calling `has_closure_tree` method (on application code load) but some time later.

I'm using Docker Compose for development and because of that I'm launching container with Rails application immediately after container with database has started. Sometimes `has_closure_tree` will be invoked and will attempt to access DB to analyze tables before RDBMS is ready to serve clients. So, application will fail to load and application server will be terminated).

Rails itself (without closure_tree) doesn't hit the DB until first request will come, so everything works as expected even if DB was not ready at time of first request (ActiveRecord will analyze tables when DB will be ready).

Also request time (or first model access time) configuration should fix other issues like #214

Thank you for closure_tree!

**Comment by mceachen** [comment]
Great idea; it'd be great to get rid of the hackiness around initialization. 

Do you know of a reliable loading event I can register with, or would I need to add an `initialize` call to every method in `closure_tree` (which would be pretty terrible and error prone).

If you feel up to it, have a swing at a pull request!

**Comment by n-rodriguez** [comment]
Hi there! Got the same problem here when testing my app with Rails 5.2.0.rc2.

**Comment by n-rodriguez** [comment]
I could workaround it with monkey patching :

```
# frozen_string_literal: true

require 'closure_tree/support_flags'
require 'closure_tree/support_attributes'

module MyApp
  module CoreExt
    module ClosureTreePatch

      module SupportFlagsPatch
        def order_is_numeric?
          # return if not connected to DB (on rake db:setup for instannce)
          return false unless ::ActiveRecord::Base.connected?

          # The table might not exist yet (in the case of ActiveRecord::Observer use, see issue 32)
          return false if !order_option? || !model_class.table_exists?
          c = model_class.columns_hash[order_column]
          c && c.type == :integer
        end
      end

      module SupportAttributesPatch
        def quoted_hierarchy_table_name
          # return if not connected to DB (on rake db:setup for instannce)
          return unless ::ActiveRecord::Base.connected?
          connection.quote_table_name hierarchy_table_name
        end
      end

    end
  end
end

unless ClosureTree::SupportFlags.included_modules.include?(MyApp::CoreExt::ClosureTreePatch::SupportFlagsPatch)
  ClosureTree::SupportFlags.send(:prepend, MyApp::CoreExt::ClosureTreePatch::SupportFlagsPatch)
end

unless ClosureTree::SupportAttributes.included_modules.include?(MyApp::CoreExt::ClosureTreePatch::SupportAttributesPatch)
  ClosureTree::SupportAttributes.send(:prepend, MyApp::CoreExt::ClosureTreePatch::SupportAttributesPatch)
end
```

**Comment by mceachen** [comment]
@n-rodriguez no need to monkeypatch--a PR would be great. 

Turns out I didn't know about `.connected?` when I wrote this part. (and it looks like it was [added way back in 2.3](https://apidock.com/rails/ActiveRecord/Base/connected%3F/class)!)

**Comment by Envek** [comment]
Also note that there is some official™ way have been discovered with `load_schema!` class-level method: https://github.com/rails/rails/pull/31681#issuecomment-357113030 (maybe it helps)

**Comment by n-rodriguez** [comment]
Hi! The PR is here https://github.com/ClosureTree/closure_tree/pull/306 :)
IMHO I don't think `load_schema!`  is the way to go. I've finally make the tests pass on my app and so far it looks good. it's not yet in staging or in production but the CI pass \o/
Actually I remembered I use the same trick in my fork or [RoyceRole](https://github.com/jbox-web/Royce/blob/master/lib/royce/macros.rb#L30)

**Comment by n-rodriguez** [comment]
> IMHO I don't think `load_schema!` is the way to go.

IMHO I DO think `load_schema` is the way to go. :)

**Comment by n-rodriguez** [comment]
See: https://github.com/jbox-web/royce/blob/master/lib/royce/schema.rb
