### ISSUE TITLE
Your Opinion Please: What would you like to happen to ClosureTree?

### ISSUE THREAD

**Issue by mceachen** [ClosureTree/closure_tree#277]
So... it turns out I haven't used Rails in production since 2013, and don't see myself using it in the future. I'm opening this issue as a way to discuss what people want to do with this codebase. 

Please upvote or downvote the comment with the solution you like best.

Thanks to the > 50 engineers that have contributed features and bugfixes over the past 6 years, and hundreds more that took the time to document and work through issues!

**Comment by mceachen** [comment]
Simple solution: I move this project to a new ClosureTree organization and hand it off to a couple maintainers. @seuros would you take the reigns? Any other volunteers?

**Comment by patrickdavey** [comment]
I've only _just_ started using ClosureTree.. but moving it to an organisation sounds like a good move. I don't have the time (or quite possibly skills!) to help maintain it unfortunately.

**Comment by mobilutz** [comment]
@mceachen After the creation if the ClosureTree organization, the links in rubygems do not work anymore.
Maybe its a good idea to release a new version so rubygems picks up the changes.
https://rubygems.org/gems/closure_tree

**Comment by mceachen** [comment]
@mobilutz I'm seeing proper 301 redirects from https://github.com/mceachen/closure_tree go to the new URL. What link is broken?

**Comment by mobilutz** [comment]
@mceachen This one does not work: http://mceachen.github.io/closure_tree/ And it is the first link in the sidebar inside the `Links` section.

**Comment by mceachen** [comment]
@mobilutz fixed the broken link, thanks for the report.

**Comment by mceachen** [comment]
(elided helpful broken link report from @mobilutz to keep this issue thread concise)

**Comment by seuros** [comment]
I will handle the future releases and try to get people to help with the maintenance.

**Comment by mceachen** [comment]
@seuros Excellent! I moved `with_advisory_lock` into this new org, too, given that closure_tree depends on it.

**Comment by hayesr** [comment]
I really like this gem and have used it on projects in the past. I'm too busy at the moment, but I'd be interested in helping in the future.

**Comment by uhlenbrock** [comment]
Howdy, folks! I'm here and would like to help. I rely pretty heavily on this project, and I appreciate all the hard work that has gone into building it.

Thanks for merging my PR. Please feel free to tag me on issues.

**Comment by mceachen** [comment]
I did some tagging and closing of open issues several months ago--if you want to tag ancient issues as stale before you close them, I think that's reasonable (especially if it's just a question or a feature request), but I think open feature requests aren't necessarily bad.

**Comment by tomaadland** [comment]
I would like to help out as we rely on this gem. I'm as everybody else extremely busy at the moment , but will find some time to give a hand. Anyone up for doing a distributed meetup (google hangout, skype, etc.. ?) as a starting point ?

**Comment by mceachen** [comment]
@tomaadland I think more eyes on https://github.com/ClosureTree/closure_tree/issues/240 would be great, if you have time, and I'll happily add you as a committer after 1 or 2 PRs (like I have with other authors). I set up [gitter](https://gitter.im/closure_tree/Lobby) a while back (and linked to it from the readme) if you'd like to chat, but I expect people are on very different timezones.

**Comment by tomaadland** [comment]
@mceachen Absolutely, I would suspect different timezones. The #240 is the one issue I have problems with myself so have been looking at that. I'll continue the thread there.

**Comment by hellekin** [comment]
Hi, I'm starting a new rails 5 app and was wondering if I should use this gem since the maintainership is not clear yet. Is @seuros still committed to maintaining it?

**Comment by seuros** [comment]
@hellekin yes. I will release the cleaned version this weekend. 
Rails 5 is already supported and tested.

**Comment by Dimetriu** [comment]
It sounds really perspective. I start to use it in my dropbox-like app, good job guyz!

**Comment by laiskajoonas** [comment]
> @hellekin yes. I will release the cleaned version this weekend.
> Rails 5 is already supported and tested.

Any chance you you get the release done? I've been using the master branch in production for a good while now. And it seems pretty stable at least in my use case. I'm running rails 5.2.

**Comment by seuros** [comment]
Right now.
