### ISSUE TITLE
Add migration's version for Rails 5 support

### ISSUE THREAD

**Issue by oniksfly** [ClosureTree/closure_tree#283]
Generating migration out-of-box with command `rails g closure_tree:migration tag` creates migration without pointing at version: 
```
class CreateTagHierarchies < ActiveRecord::Migration
   def change
   end
end
```

Starting from Rails 5 it's required to add migration's version for back support, so it's seems like template [`lib/generators/closure_tree/templates/create_hierarchies_table.rb.erb`](https://github.com/ClosureTree/closure_tree/blob/master/lib/generators/closure_tree/templates/create_hierarchies_table.rb.erb) should looks like (only first line was changed):

```
class <%= migration_class_name %> < ActiveRecord::Migration[4.2]
  def change
    create_table :<%= migration_name %>, id: false do |t|
      t.<%= primary_key_type %> :ancestor_id, null: false
      t.<%= primary_key_type %> :descendant_id, null: false
      t.integer :generations, null: false
    end

    add_index :<%= migration_name %>, [:ancestor_id, :descendant_id, :generations],
      unique: true,
      name: "<%= file_name %>_anc_desc_idx"

    add_index :<%= migration_name -%>, [:descendant_id],
      name: "<%= file_name %>_desc_idx"
  end
end
```

At this moment we've got an exception `StandardError: An error has occurred, this and all later migrations canceled: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for …`.

**Comment by seuros** [comment]
Fixed in v7.0.0 and master
