### ISSUE TITLE
undefined method `find_each' for []:Array

### ISSUE THREAD

**Issue by adewinter** [ClosureTree/closure_tree#286]
Hi,

After installing the `closure_tree` gem (with bundler) and adding the `acts_as_tree` line to my model (and performing the associated migrations), I get the following error when attempting to create a node.  (The model I'm attempting to use `closure_tree` with in this case is called `Item`):

```
> Item.create merchant_item_id: 1, name: "lol"
NoMethodError: undefined method `find_each' for []:Array
Did you mean?  find_all
from /Users/antondewinter/.rvm/gems/ruby-2.4.2/gems/closure_tree-6.6.0/lib/closure_tree/hierarchy_maintenance.rb:85:in `block in rebuild!'
```

`merchant_item_id` is a  required field in the model (and I think is unrelated to this error).  When I first tried to create a node, the `item_hierarchies` table was empty.  

I tried to trace this error to a recent change in the `closure_tree` codebase, and I think it is related to [this commit](https://github.com/ClosureTree/closure_tree/commit/1a847c3c30d0dcc347c4c386ef2087f4d15e21bf#diff-693c6ab46fe400dd004a79a24ab8d56bR82).  Which sort of makes sense: when there are no children, an empty array is returned (instead of an AR association), meaning one cannot use `#find_each`; which would cause this error.  When I modified Line 85 back to just using regular `.each`, there were no errors and I was able to create nodes.

Is this a bug or am I doing something wrong?

Thanks!

**Comment by mceachen** [comment]
Nice sleuthing!

I was going to suggest that it's a rails version issue with [find_each](https://apidock.com/rails/ActiveRecord/Batches/find_each), but that seems to be fairly stable since v3.0. Here's [the PR associated with that diff](https://github.com/ClosureTree/closure_tree/pull/258). If you think it should be configurable, perhaps, I'd be happy to accept a PR.

**Comment by adewinter** [comment]
I made a mistake.  It turns out there was code in my codebase that overrode the `#children` method, causing these issues.  Once I removed that bit of code, there were none of the errors I described above.  Sorry for leading you on a goose chase!  

I'm going to go ahead and close this ticket.

**Comment by nbekirov** [comment]
I was just looking into this and was about to post that it's not reproducible on Rails 5.1.4... 😃
