### ISSUE TITLE
Could not find generator 'closure_tree:migration'

### ISSUE THREAD

**Issue by ltfschoen** [ClosureTree/closure_tree#289]
I've tried installing on a Rails 5.1.3 project as follows:
* Adding to Gemfile `gem 'closure_tree', '~> 6.6.0'`
* Running `bundle install`
* Modifying an existing migration by adding `t.integer :parent_id, null: true` to it
```
class CreateSkillTokens < ActiveRecord::Migration[5.1]
  def change
    create_table :skill_tokens do |t|
      t.string :name
      t.integer :parent_id, null: true
      t.references :user_profile, foreign_key: true

      t.timestamps
    end
  end
end
```
* Adding `has_closure_tree` to the model
```
class SkillToken < ActiveRecord::Base
  belongs_to :profile, class_name: 'UserProfile'
  validates_presence_of :name

  has_closure_tree
end
```

But when I run `bundle exec rails g closure_tree:migration skill_token` it gives error:
```
$ bundle exec rails g closure_tree:migration skill_token
Running via Spring preloader in process 50346
Could not find generator 'closure_tree:migration'. Maybe you meant 'active_record:migration', 'migration' or 'test_unit:integration'
Run `rails generate --help` for more options.
```

**Comment by nbekirov** [comment]
Strange error, check this out #283

**Comment by ltfschoen** [comment]
[Here's the branch of my GitHub repo where I'm getting the error](https://github.com/peerism/peerai-backend/compare/master...feature/12-associations-for-sub-skill-tokens-using-closuretree-gem?expand=1)

**Comment by ltfschoen** [comment]
@nbekirov The cause of the error was the Spring. I encountered a different error when trying the [ActsAsTree Gem here](https://github.com/amerine/acts_as_tree/issues/71), which was also caused by Spring. 
The solution was to remove Spring from the Gemfile as follows, then run `bundle install`. My Gemfile was changed as follows:
```
group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring

  # Remove since causes error: `Running via Spring preloader in process 59266; Could not find generator 'closure_tree:migration'. Maybe you meant 'active_record:migration', 'migration' or 'test_unit:integration'` when running `$ bundle exec rails g closure_tree:migration skill_token`
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
end
```
