### ISSUE TITLE
Rails 5.2

### ISSUE THREAD

**Issue by johan-smits** [ClosureTree/closure_tree#305]
217162cd8a9976f52cb129dbf3959f62f651891f you fixed #296.
Rails 5.2 is not officially released. Could you also bump/release your gem to include this fix?

**Comment by mjy** [comment]
Are there other blocking issues that are known?  What's the release pattern, do you typically fork a branch with the new environment and add it to the CI for testing?

**Comment by grk** [comment]
I've been testing the current master for a few days and for us, everything works fine.

**Comment by mceachen** [comment]
@grk and @n-rodriguez could you guys check out #308 and #309 ? I'll merge that if the three of you all agree that the PR is correct.

(I'm also looking for more committers for ClosureTree!)

**Comment by n-rodriguez** [comment]
> could you guys check out #308 and #309 ?

sure

**Comment by mceachen** [comment]
Builds on 5.2 have been green for a while. Closing. Thanks for everyone's help. Time for v7.0.0!

**Comment by timdown** [comment]
Any news on the release of 7.0.0?
