### ISSUE TITLE
FactoryBot linter failing for a model that uses closure_tree

### ISSUE THREAD

**Issue by bijalpatel13** [ClosureTree/closure_tree#308]
I have a model that I am using closure tree with and have a factory created for it. We have a spec that does `FactoryBot.lint FactoryBot.factories`, which is now failing because of the error below.
```
expected no Exception, got #<FactoryBot::InvalidFactoryError: The following factories are invalid:

* display_logic - undefined local variable or method `_ct_reorder_prior_siblings_if_parent_changed' for #<Registries::DisplayLogic:0x00007ffb3bc1c828> (NameError)
```
[This](https://github.com/ClosureTree/closure_tree/commit/cb7363ea40d09ab03bae906c33f73e51b590978e) was the last commit where the factory was passing the linter. Any suggestions on how to fix this?

rails (5.2.0)
factory_bot (4.8.2)
factory_bot_rails (4.8.2)

**Comment by bijalpatel13** [comment]
@chunlea I digged into it and found out it was [this change](https://github.com/ClosureTree/closure_tree/issues/308#issuecomment-388027000) that broke it. I am still trying to figure out why ActiveRecord is not connected in my test environment.

**Comment by n-rodriguez** [comment]
> I am still trying to figure out why ActiveRecord is not connected in my test environment.

See https://github.com/ClosureTree/closure_tree/issues/264 : 

> Rails itself (without closure_tree) doesn't hit the DB until first request will come, so everything works as expected even if DB was not ready at time of first request (ActiveRecord will analyze tables when DB will be ready).
