### ISSUE TITLE
Error when sorting by column "name" and using includes(:self_and_descendants)

### ISSUE THREAD

**Issue by alexbrand** [ClosureTree/closure_tree#31]
I have a category hierarchy and was trying to avoid N+1 queries by doing:

```
 Category.includes(:self_and_descendants).find(params[:id])
```

However, I am getting an error:

```
ActiveRecord::StatementInvalid: PG::Error: ERROR:  
    column "name" does not exist
```

Here is the SQL being generated

```
 Category Load (0.4ms)  SELECT "categories".*
    FROM "categories" 
    WHERE "categories"."id" = $1 LIMIT 1  [["id", 5]]
 CategoryHierarchy Load (0.6ms)  SELECT "category_hierarchies".* 
   FROM "category_hierarchies" 
   WHERE "category_hierarchies"."ancestor_id" IN (5) 
   ORDER BY "category_hierarchies".generations asc, name
```

My category model has an order by:

```
  acts_as_tree :order => 'name'
```

When I get rid of the ordering it works fine.

How can I use `.includes(:self_and_descendants)` and also order by `name`? Thanks

**Comment by kapluni** [comment]
What if you are loading more than one tag at once? is there a way to load all the ancestors (or all the roots) in a single query?
