### ISSUE TITLE
Rails 5.2 issues - next release?

### ISSUE THREAD

**Issue by mallorybulkley** [ClosureTree/closure_tree#318]
It seems like there are commits in master that fix the deprecation warnings for rails 5.2, namely 'dangerous query method' for "<model>_hierarchies.generations asc". The commit that fixes it was merged to master in February of this year (#296) but there hasn't been a new release since last July. Is there going to be another release anytime soon for the changes from the past year?

see also issues #315, #300 which reference the same warnings.

**Comment by swistaczek** [comment]
@seuros are You able to push new release to rubygems :)?

**Comment by seuros** [comment]
https://rubygems.org/gems/closure_tree/versions/7.0.0
