### ISSUE TITLE
Reason for major version bump to 7.x?

### ISSUE THREAD

**Issue by swrobel** [ClosureTree/closure_tree#331]
First of all, don't get me wrong, I'm really excited about the new release, and appreciate all of the hard work that went into it...

I'm just wondering why the major version was bumped to 7. Looking at the [changes from 6.6.0 to 7.0.0](https://github.com/ClosureTree/closure_tree/compare/v6.6.0...v7.0.0), there don't seem to be any breaking changes, as would be indicated by the version bump.

**Comment by mceachen** [comment]
Perhaps @seuros was being overly cautious? I'm not aware of breaking changes, fwiw.

**Comment by seuros** [comment]
@swrobel , sorry for delay. 
We will always bump to a major version when supporting a new version of ActiveRecord.  While support for the versions stayed the same this time. the syntax of some  files changed (Some raw sqls string are now in Arel).
If there was a regression, we won't affect people that locked their version in ~> 6.6.0 while trying to fix the bug.
