### ISSUE TITLE
Problem with uuids as primary keys

### ISSUE THREAD

**Issue by suung** [ClosureTree/closure_tree#342]
Hey

Sorry, I don't know how to go further here, i found uuid support in the changelog, but yet

```
(byebug) parent_task.children.create(user_id: parent_task.user.id, workflow_id: parent_task.workflow.id)
*** ActiveRecord::StatementInvalid Exception: PG::UndefinedFunction: ERROR:  operator does not exist: uuid = integer
LINE 5: WHERE x.descendant_id = 72337
                              ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: INSERT INTO "task_hierarchies"
  (ancestor_id, descendant_id, generations)
SELECT x.ancestor_id, '2cd4eac4-322c-47d7-91a9-73cf95eead48', x.generations + 1
FROM "task_hierarchies" x
WHERE x.descendant_id = 72337
```

rails 5.2.2
closure_tree-7.0.0

I will appreciate every help very much

**Comment by joaocvalerio** [comment]
did you runned the command `Task.rebuild!`

**Comment by mbajur** [comment]
Hey there! I'm gonna bump that thread - i am facing the same issue. Both when creating new records and when using `Model.rebuild!`.

- Rails 6.0.3.7
- closure_tree 7.1.0

**Comment by seuros** [comment]
@mbajur  You need to drop the hierarchies table and recreate it with uuid types. 
Add foreign keys to be sure that the columns are connect.

**Comment by mbajur** [comment]
I didn't did anything special - i had an app using UUIDs as a primary keys - i installed closure_tree using a provided tutorial and that's the output visible above. I can see in the migrations that hierarchy table is using UUID as foreign keys types.

![image](https://user-images.githubusercontent.com/581569/121248248-81edc580-c8a3-11eb-883e-48c00d97e827.png)

**Comment by seuros** [comment]
Either your app is using the cache or your database is not uptodate.

Try to add those fkeys: 
```
  add_foreign_key "ap_object_hierarchies", "ap_objects", column: "ancestor_id"
  add_foreign_key "ap_object_hierarchies", "ap_objects", column: "descendant_id"
```

 I use UUID all the time with closure-tree

**Comment by mbajur** [comment]
Yes, sorry, that was obviously my mistake. I forgot to change `parent_id` column to `UUID`
