### ISSUE TITLE
Ruby 2.7 deprecation warning about keyword parameters

### ISSUE THREAD

**Issue by mfichman** [ClosureTree/closure_tree#364]
We recently upgraded to Ruby 2.7, and `closure_tree` calls a method in active record without using the splat operator `**` which will be required in this case in Ruby 3.0. More info here: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0

```
/app/vendor/bundle/ruby/2.7.0/gems/closure_tree-7.1.0/lib/closure_tree/model.rb:9: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/associations.rb:1657: warning: The called method `belongs_to' is defined here
```

**Comment by phlegx** [comment]
@mfichman in the master branch all changes are made for Ruby 2.7.
@seuros can this be released please? Thx!

**Comment by seuros** [comment]
sure thing. I will schedule a release this weekend for many gems .

**Comment by tindron** [comment]
@seuros Any progress on the release?
