### ISSUE TITLE
parallel_test fails

### ISSUE THREAD

**Issue by jkraemer** [ClosureTree/closure_tree#427]
I have tried with PostgreSQL 11 as well as MariaDB 11, both seem to never pass this test case. Example logs attached.

I have tried to debug it with psql and to me it looks like it's more an issue with the test infrastructure than with the library itself. Apparently data created in one test case leaks into the next and / or the worker threads do not "see" records created in the main thread.

At this point I'd basically like to know if I am doing something wrong or if this is something that needs to be fixed.

[postgres_11.log](https://github.com/ClosureTree/closure_tree/files/13421598/postgres_11.log)
[mariadb_11.log](https://github.com/ClosureTree/closure_tree/files/13421601/mariadb_11.log)

**Comment by jkraemer** [comment]
setting the DatabaseCleaner strategy to `:truncation` instead of `:transaction` in `test/test_helper.rb` seems to fix this. I added this to my PR #426

**Comment by seuros** [comment]
thank you, i merged the tests.
