### ISSUE TITLE
Negative position shows child before parent in `roots_and_descendants_preordered`

### ISSUE THREAD

**Issue by leonelgalan** [ClosureTree/closure_tree#49]
When position is negative the child showed before the parent in `roots_and_descendants_preordered`, `self_and_descendants_preordered` it's behaving correctly (displaying Parent first, followed by its children)

```
  Child A
Parent
  Child B
  Child C
```

**Comment by leomayleomay** [comment]
This is still not working quite well with RankedModel, it works great before I adjust the position of an item, it breaks miserably after I adjust the position, and the new `row_order` became a negative number, I am not appending/prepending a child/sibling, I am just re-arranging the position.

**Comment by leomayleomay** [comment]
finally, i figured this part out with overwriting the method in the model, it's slow (because it's recursive), but it works

```
def self_and_descendents_preordered
  result = [self]

  children.each do |child|
    result += child.self_and_descendents_preordered
  end

  result
end
```
