### ISSUE TITLE
Add a caveat about default_scope to the README?

### ISSUE THREAD

**Issue by bithive** [ClosureTree/closure_tree#86]
I just spent way too long trying to figure out why closure_tree wasn't working for me; it turns out that I had declared

`default_scope { order('id asc') }`

in my model and it was causing trees to misbehave when they contained children whose IDs where less than that of their parent.  Perhaps my blunder can be documented to help others avoid similar headaches.

**Comment by matsrietdijk** [comment]
@mceachen would it be an idea to prefix the `order` calls used for closure_tree with `reorder('')` to clear any orders set by default? I ran into this problem when calling `self_and_ancestors` while having a default scope ordering on a custom attribute on my model.

**Comment by jmuheim** [comment]
I've come here from the README. But I don't really get the point: what exactly is the problem? I'm in the process of choosing a gem for creating trees, and I'd like to choose closure_tree, but first I'd like to know what the caveat is with this issue.

Thanks for explaining a bit deeper.

**Comment by mceachen** [comment]
My experience with default_scope is that there are so many gotchas with
this misfeature that it's generally good advice to avoid it.

The issue with closure_tree is that the quite complicated query generation
in this gem can't incorporate arbitrary SQL from the default scope and
generate valid queries.

**Comment by kaoru** [comment]
I suspect this is the problem I'm having too. I've got a default scope thanks to the [paranoia](https://github.com/rubysherpas/paranoia) gem, and even though none of the records I'm trying to add to a hierarchy it seems like the whole thing isn't working properly with the scope set 😢 

I wonder if this could be made to work by having an option to `has_closure_tree` that would make it always use `#unscoped`.
